### ISSUE TITLE
Error launching freon

### ISSUE THREAD

**Issue by pjmolina** [LionWeb-io/property-demo#23]
Hi! Followed the steps on Readme to setup and run the demo. Got an error with freon/rollup in the final step `yarn dev`:

```bash
$ yarn dev
yarn run v1.22.21
$ rollup -c -w
rollup v2.53.1
bundles src/webapp/main.ts → public\build\bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module './internal' or its corresponding type declarations.
src\picode\language\gen\PROPSLanguage.ts: (13:29)

13 import * as MyLanguage from "./internal";
                               ~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module '../../stdlib/gen/PROPSStdlib' or its corresponding type declarations.
src\picode\language\gen\PROPSLanguage.ts: (14:29)

14 import { PROPSStdlib } from "../../stdlib/gen/PROPSStdlib";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module '../../picode/config/gen/PROPSEnvironment' or its corresponding type declarations.
src\webapp\config\WebappConfiguration.ts: (2:34)

2 import { PROPSEnvironment } from "../../picode/config/gen/PROPSEnvironment";
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(!) Plugin svelte: A11y: noninteractive element cannot have nonnegative tabIndex value
node_modules\@smui\card\dist\PrimaryAction.svelte
1: <div
   ^
2:   bind:this={element}
3:   use:useActions={use}
[!] Error: Could not resolve '../../picode/config/gen/PROPSEnvironment' from src\webapp\config\WebappConfiguration.ts
Error: Could not resolve '../../picode/config/gen/PROPSEnvironment' from src\webapp\config\WebappConfiguration.ts
    at error (Z:\explore\property-demo\freon\node_modules\rollup\dist\shared\rollup.js:151:30)
    at ModuleLoader.handleResolveId (Z:\explore\property-demo\freon\node_modules\rollup\dist\shared\rollup.js:19797:24)
    at D:\explore\property-demo\freon\node_modules\rollup\dist\shared\rollup.js:19746:22
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at ModuleLoader.fetchStaticDependencies (Z:\explore\property-demo\freon\node_modules\rollup\dist\shared\rollup.js:19744:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (D:\explore\property-demo\freon\node_modules\rollup\dist\shared\rollup.js:19720:9)
    at async Promise.all (index 28)
    at ModuleLoader.fetchStaticDependencies (Z:\explore\property-demo\freon\node_modules\rollup\dist\shared\rollup.js:19744:34)
```

Looks like the `./internal` folder is missing in the repository.

Could you provide ahint to unblock me? Thanks

**Comment by joswarmer** [comment]
I think the README is incomplete. For Freon it says:

```
cd freon
yarn install 
```
This should be
```
cd freon
yarn install
yarn generate
yarn prepare-app
yarn dev
```
The additional step generate the code and the styling of the web app. 

The README in the freon folder does include these steps.
Note that there are more steps in the `freon/README` to ensure Freon connects with MPS.

**Comment by pjmolina** [comment]
Make sense. Building now. Thanks!
